service: hcrawl
app: hcrawl-app
org: svarty1

provider:
  name: aws
  runtime: nodejs12.x
  profile: home

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "dynamodb:BatchGetItem"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "lambda:InvokeFunction"
      Resource:
        - arn:aws:s3:::hcrawl
        - arn:aws:dynamodb:us-east-1:895013772455:table/ArchiveRequests
        - arn:aws:dynamodb:us-east-1:895013772455:table/ArchiveDownloads
        - arn:aws:lambda:us-east-1:895013772455:function:hcrawl-dev-archiveRequest
        - arn:aws:lambda:us-east-1:895013772455:function:hcrawl-dev-archiveDownload
        - arn:aws:lambda:us-east-1:895013772455:function:hcrawl-dev-processHistory 
        - arn:aws:lambda:us-east-1:895013772455:function:hcrawl-dev-downloadMix

plugins:
  - serverless-offline

environment:
  DEV: dev
  APP: hcrawl

functions:
  downloadMix:
    handler: src/mix.download
    memorySize: 2048
    timeout: 15
    events:
      - http:
          path: mix/download
          method: post

    environment:
      BUCKET: hcrawl

  archiveRequest:
    handler: src/archive.request
    memorySize: 256
    timeout: 6
    events:
      - http:
          path: archive/request
          method: get

  archiveDownload:
    handler: src/archive.download
    timeout: 6
    events:
      - http:
          path: archive/download
          method: get

  processHistory:
    handler: src/history.process
    timeout: 15
